import {esc, icon, DESKTOPS, WALLPAPERS, download, exportVirtualFile, safeAction} from './ui.js';

export function createDesktopApps({system, PACKAGE_REGISTRY, openApp, toast, applySettings, renderLauncherApps}) {
  const run = action => safeAction(action, toast);
  function renderWelcome(root) {
    root.innerHTML = `<div class="welcome"><div class="welcome-eyebrow"><span class="welcome-badge"><i class="status-dot"></i> FLINUX 1.0 · GLIMTEN</span><img src="assets/mark.svg" alt="" width="42" height="42"></div><h1>Lite Linux.<br>Mycket <span>leende.</span></h1><p>Välkommen till <b>flinux</b>. Ett eget litet Linux att utforska, anpassa och göra till ditt. Helt i webbläsaren.</p><div class="welcome-divider"></div><div class="quick-actions"><button data-open="terminal"><span class="action-icon mint">${icon('terminal')}</span><strong>Börja med en rad</strong><small>Öppna terminalen ${icon('arrow-right')}</small></button><button data-open="discover"><span class="action-icon peach">${icon('packages')}</span><strong>Hitta något nytt</strong><small>Utforska paket ${icon('arrow-right')}</small></button><button data-open="settings"><span class="action-icon lavender">${icon('settings')}</span><strong>Gör det till ditt</strong><small>Byt skrivbord ${icon('arrow-right')}</small></button></div><div class="welcome-bottom"><label class="welcome-toggle"><input type="checkbox" data-show-welcome ${system.state.settings.showWelcome!==false?'checked':''}> Visa vid start</label><span>Flin + Linux = ${icon('linux')} <b>Det glada linuxet</b></span></div></div>`;
    root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openApp(b.dataset.open));
    root.querySelector('[data-show-welcome]').onchange=e=>{system.state.settings.showWelcome=e.target.checked;system.save();};
  }

  function renderFiles(root, options={}) {
    let current=system.normalize(options.path||system.state.user.home), selected=null, showHidden=false;
    root.innerHTML=`<div class="file-manager"><div class="toolbar"><button data-nav="up" aria-label="Överordnad mapp">↑</button><button data-nav="home" aria-label="Hemmapp">⌂</button><form class="path-form"><input class="pathbar" aria-label="Sökväg"></form><button data-new-file title="Ny textfil">+ Fil</button><button data-new-folder title="Ny mapp">+ Mapp</button><button data-hidden title="Visa dolda filer" aria-pressed="false">· · ·</button></div><div class="file-layout"><aside class="sidebar"><h3>Platser</h3>${[['Hemma',''],['Skrivbord','Desktop'],['Dokument','Documents'],['Hämtningar','Downloads'],['Bilder','Pictures'],['Filsystem','/']].map(([label,path])=>`<button data-place="${path}">${icon(path==='Pictures'?'image':'files')}${label}</button>`).join('')}</aside><div class="files" aria-label="Filer"></div></div><div class="file-status"><span data-file-count></span><div><button class="text-button" data-rename disabled>Byt namn</button><button class="text-button" data-export disabled>Exportera</button><button class="text-button" data-delete disabled>Ta bort</button></div></div></div>`;
    const files=root.querySelector('.files'), pathbar=root.querySelector('.pathbar');
    const updateSelection=()=>{root.querySelector('[data-rename]').disabled=!selected;root.querySelector('[data-delete]').disabled=!selected;root.querySelector('[data-export]').disabled=!selected||system.getNode(`${current}/${selected}`)?.type!=='file';};
    function draw(){
      if(system.getNode(current)?.type!=='dir')current=system.state.user.home;
      pathbar.value=current; files.innerHTML=''; selected=null; updateSelection();
      const names=system.list(current).filter(n=>showHidden||!n.startsWith('.'));
      root.querySelector('[data-file-count]').textContent=`${names.length} objekt`;
      root.querySelectorAll('[data-place]').forEach(b=>b.classList.toggle('active',current===(b.dataset.place==='/'?'/':system.normalize(`${system.state.user.home}/${b.dataset.place}`))));
      if(!names.length)files.innerHTML=`<div class="empty-state">${icon('files')}<strong>Gott om plats för något nytt.</strong><small>Skapa en fil eller mapp här.</small></div>`;
      for(const name of names){
        const path=system.normalize(`${current}/${name}`), node=system.getNode(path), b=document.createElement('button');
        b.className='file-item';b.innerHTML=`<span class="file-icon ${node.type==='dir'?'folder':'document'}">${icon(node.type==='dir'?'files':/\.(png|svg|jpe?g|webp)$/i.test(name)?'image':'editor')}</span><span>${esc(name)}</span>`;
        b.onclick=()=>{selected=name;files.querySelectorAll('.file-item').forEach(x=>x.classList.toggle('selected',x===b));updateSelection();};
        const enter=()=>{if(node.type==='dir'){current=path;draw();}else if(node.content?.startsWith('flinux-wallpaper:'))openApp('image-viewer',{wallpaper:node.content.split(':')[1]});else if(/^data:image\/(png|jpeg|webp);base64,/.test(node.content))openApp('image-viewer',{path});else if(/\.md$/i.test(name)&&system.state.installed.includes('markdown'))openApp('markdown',{path});else openApp('kate',{path});};
        b.ondblclick=enter;b.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();enter();}};files.append(b);
      }
    }
    root.querySelector('.path-form').onsubmit=e=>{e.preventDefault();run(()=>{const path=system.normalize(pathbar.value,current);if(system.getNode(path)?.type!=='dir')throw new Error('Katalogen finns inte');current=path;draw();});};
    root.querySelector('[data-nav=up]').onclick=()=>{current=system.normalize(`${current}/..`);draw();};
    root.querySelector('[data-nav=home]').onclick=()=>{current=system.state.user.home;draw();};
    root.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{current=b.dataset.place==='/'?'/':system.normalize(`${system.state.user.home}/${b.dataset.place}`);draw();});
    const newEntry=dir=>run(()=>{const name=prompt(dir?'Namn på den nya mappen:':'Namn på den nya filen:',dir?'Ny mapp':'anteckning.txt');if(!name)return;if(name.includes('/')||['.','..'].includes(name))throw new Error('Ange ett namn utan snedstreck');const path=`${current}/${name}`;if(system.getNode(path))throw new Error('Namnet finns redan');if(dir)system.mkdir(path);else {system.writeFile(path,'');openApp('kate',{path});}});
    root.querySelector('[data-new-folder]').onclick=()=>newEntry(true);root.querySelector('[data-new-file]').onclick=()=>newEntry(false);
    root.querySelector('[data-hidden]').onclick=e=>{showHidden=!showHidden;e.currentTarget.setAttribute('aria-pressed',String(showHidden));draw();};
    root.querySelector('[data-delete]').onclick=()=>run(()=>{if(selected&&confirm(`Ta bort ${selected} från det virtuella filsystemet?`))system.remove(`${current}/${selected}`);});
    root.querySelector('[data-rename]').onclick=()=>run(()=>{if(!selected)return;const name=prompt('Nytt namn:',selected);if(!name||name===selected)return;if(name.includes('/')||['.','..'].includes(name))throw new Error('Ogiltigt filnamn');if(system.getNode(`${current}/${name}`))throw new Error('Namnet finns redan');system.move(`${current}/${selected}`,`${current}/${name}`);});
    root.querySelector('[data-export]').onclick=()=>{const node=system.getNode(`${current}/${selected}`);if(node?.type==='file')exportVirtualFile(selected,node.content);};
    const unsubscribe=system.onChange(draw);draw();return unsubscribe;
  }

  function renderKate(root, options={}) {
    let path=options.path||`${system.state.user.home}/Documents/anteckningar.txt`,dirty=false;
    root.innerHTML=`<div class="editor"><div class="toolbar"><button data-save class="primary">Spara</button><button data-save-as>Spara som…</button><div class="pathbar">${esc(path)}</div><button data-download title="Ladda ner textfil">↓</button></div><textarea aria-label="Filens innehåll" spellcheck="false" placeholder="En tom sida. Alla möjligheter."></textarea><div class="editor-status"><span data-save-status>Sparad</span><span data-position></span></div></div>`;
    const area=root.querySelector('textarea');area.value=system.getNode(path)?.content||'';
    const status=()=>{root.querySelector('[data-save-status]').textContent=dirty?'Osparade ändringar':'Sparad';root.querySelector('[data-position]').textContent=`${area.value.split('\n').length} rader · ${area.value.length} tecken`;};
    const save=()=>run(()=>{system.writeFile(path,area.value);dirty=Boolean(system.storageError);status();if(system.storageError)root.querySelector('[data-save-status]').textContent='Endast sparad i denna session';toast(system.storageError||'Filen är sparad');});
    area.oninput=()=>{dirty=true;status();};area.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();}if(e.key==='Tab'){e.preventDefault();area.setRangeText('  ',area.selectionStart,area.selectionEnd,'end');dirty=true;status();}};
    root.querySelector('[data-save]').onclick=save;
    root.querySelector('[data-save-as]').onclick=()=>run(()=>{const next=prompt('Spara till sökväg:',path);if(!next)return;const normalized=system.normalize(next);if(normalized!==path&&system.getNode(normalized)&&!confirm('Skriva över den befintliga filen?'))return;system.writeFile(normalized,area.value);path=normalized;root.querySelector('.pathbar').textContent=path;dirty=Boolean(system.storageError);status();if(system.storageError)root.querySelector('[data-save-status]').textContent='Endast sparad i denna session';});
    root.querySelector('[data-download]').onclick=()=>download(path.split('/').pop(),area.value);
    status();
  }

  function renderDiscover(root) {
    let filter='all',query='';
    root.innerHTML=`<div class="discover-layout"><aside class="sidebar"><h3>Ditt bibliotek</h3>${[['all','packages','Utforska'],['installed','check','Installerat'],['desktop','fullscreen','Skrivbord'],['terminal','terminal','Terminal'],['apps','games','Program & spel']].map(([id,i,name])=>`<button data-filter="${id}" class="${id==='all'?'active':''}">${icon(i)}${name}</button>`).join('')}<div class="repo-label"><i class="status-dot"></i> flinux / main<small>Lokalt paketarkiv</small></div></aside><section class="discover-main"><div class="section-eyebrow">PAKETHANTERARE</div><h2>Mer att upptäcka.</h2><p>Små paket. Nya möjligheter.</p><div class="package-feature"><div><span>DITT SKRIVBORD, DINA REGLER</span><h3>Prova en annan vy.</h3><p>Från lugna GNOME till plattor i i3.</p><button class="button" data-explore-desktop>Utforska skrivbord ${icon('arrow-right')}</button></div><div class="mini-desktop" aria-hidden="true"><i></i><i></i><i></i><b>i3</b></div></div><label class="search-field"><span>${icon('search')}</span><input type="search" data-package-search placeholder="Sök paket, program och verktyg…" aria-label="Sök paket"></label><div class="list-heading"><h3 data-list-title>Alla paket</h3><span data-package-count></span></div><div class="package-list"></div></section></div>`;
    function draw(){
      const list=root.querySelector('.package-list');list.innerHTML='';
      const entries=Object.entries(PACKAGE_REGISTRY).filter(([name,p])=>(filter==='all'||filter==='installed'&&system.state.installed.includes(name)||filter==='desktop'&&p.desktop||filter==='terminal'&&p.command||filter==='apps'&&p.app)&&`${name} ${p.description}`.toLowerCase().includes(query));
      root.querySelector('[data-package-count]').textContent=`${entries.length} paket`;
      root.querySelector('[data-list-title]').textContent={all:'Alla paket',installed:'Installerade paket',desktop:'Skrivbordsmiljöer',terminal:'Terminalverktyg',apps:'Program & spel'}[filter];
      for(const [name,p] of entries){const installed=system.state.installed.includes(name),card=document.createElement('article');card.className='package-card';card.dataset.package=name;card.innerHTML=`<div class="package-icon ${p.desktop?'lavender':p.app?'peach':'mint'}">${icon(p.desktop?'fullscreen':p.app?'packages':'terminal')}</div><div class="package-info"><strong>${esc(name)} <small>${esc(p.version)}</small></strong><p>${esc(p.description)}</p><small>${p.size} kB${p.dependencies?.length?` · Kräver ${p.dependencies.map(esc).join(', ')}`:''}</small></div><div class="package-actions">${installed&&p.app?'<button class="text-button" data-launch>Öppna ↗</button>':''}<button class="button ${installed?'installed':'install-button'}" data-install ${p.core&&installed?'disabled':''}>${installed?p.core?'Systempaket':'Ta bort':'+ Installera'}</button></div>`;
        card.querySelector('[data-install]').onclick=()=>run(()=>{toast(installed?system.uninstall(name):system.install(name));renderLauncherApps();applySettings();});
        const launch=card.querySelector('[data-launch]');if(launch)launch.onclick=()=>openApp(p.app);list.append(card);
      }
      if(!entries.length)list.innerHTML='<div class="empty-state"><strong>Här var det tomt.</strong><small>Prova en annan sökning eller kategori.</small></div>';
    }
    const setFilter=id=>{filter=id;root.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===id));draw();};
    root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));root.querySelector('[data-explore-desktop]').onclick=()=>setFilter('desktop');root.querySelector('[data-package-search]').oninput=e=>{query=e.target.value.toLowerCase().trim();draw();};
    const unsubscribe=system.onChange(draw);draw();return unsubscribe;
  }

  function renderSettings(root) {
    root.innerHTML=`<div class="settings"><div class="section-eyebrow">PERSONLIGT, PRECIS SOM DU</div><h2>Gör dig hemmastadd.</h2><p class="muted">Ett nytt perspektiv är bara ett klick bort.</p><h3 class="settings-label">Skrivbordsmiljö</h3><div class="desktop-choices">${DESKTOPS.map(d=>`<button class="desktop-choice" data-desktop="${d.id}" style="--preview-accent:${d.color}"><div class="desktop-preview preview-${d.id}" aria-hidden="true"><i></i><i></i><i></i></div><strong>${d.name}<span data-desktop-status></span></strong><small>${d.detail}</small></button>`).join('')}</div><h3 class="settings-label">Bakgrund</h3><div class="wallpaper-choices">${WALLPAPERS.map(w=>`<button class="wallpaper-choice" data-wallpaper="${w.id}" aria-label="Välj bakgrunden ${w.name}"><img src="assets/wallpapers/${w.id}.svg" alt=""><span>${w.name}</span></button>`).join('')}</div><div class="setting-row"><div><strong>Accentfärg</strong><small>Den lilla färgklicken som gör skillnad.</small></div><div class="swatches">${[['#94dfc5','148, 223, 197','Mint'],['#a6bafa','166, 186, 250','Lavendel'],['#edc784','237, 199, 132','Sol'],['#eeaf96','238, 175, 150','Persika']].map(([c,r,n])=>`<button class="swatch" style="background:${c}" data-color="${c}" data-rgb="${r}" aria-label="${n}"></button>`).join('')}</div></div><div class="setting-row"><div><strong>Välkommen hem</strong><small>Visa välkomstfönstret vid start.</small></div><label class="switch"><input aria-label="Visa välkomstfönster" type="checkbox" data-welcome><span></span></label></div><div class="setting-row"><div><strong>Mindre rörelse</strong><small>Stäng av övergångar och animationer.</small></div><label class="switch"><input aria-label="Minska rörelse" type="checkbox" data-motion><span></span></label></div><h3 class="settings-label">Ditt virtuella system</h3><div class="setting-row"><div><strong>Ta med dig ditt flinux</strong><small>Säkerhetskopiera filer, paket och inställningar.</small></div><div class="setting-buttons"><button class="button" data-backup>Exportera</button><button class="button" data-import>Importera</button><input type="file" data-backup-file accept="application/json,.json" hidden></div></div><div class="setting-row"><div><strong>En ny början</strong><small>Radera alla sparade flinux-data i webbläsaren.</small></div><button class="text-button danger" data-reset>Återställ…</button></div><p class="shortcut-note">${icon('terminal')} <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd> terminal &nbsp; · &nbsp; <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>1–4</kbd> arbetsytor</p></div>`;
    function draw(){root.querySelectorAll('[data-desktop]').forEach(b=>{const d=DESKTOPS.find(d=>d.id===b.dataset.desktop),active=system.state.settings.desktop===d.id;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));b.querySelector('[data-desktop-status]').textContent=active?'Aktiv':system.state.installed.includes(d.package)?'Välj':'Installera';});root.querySelectorAll('[data-wallpaper]').forEach(b=>{b.classList.toggle('selected',b.dataset.wallpaper===(system.state.settings.wallpaper||'glimten'));b.setAttribute('aria-pressed',String(b.classList.contains('selected')));});root.querySelector('[data-welcome]').checked=system.state.settings.showWelcome!==false;root.querySelector('[data-motion]').checked=Boolean(system.state.settings.reduceMotion);}
    root.querySelectorAll('[data-desktop]').forEach(b=>b.onclick=()=>run(()=>{const d=DESKTOPS.find(d=>d.id===b.dataset.desktop);if(!system.state.installed.includes(d.package))system.install(d.package);system.state.settings.desktop=d.id;system.save();applySettings();toast(`Välkommen till ${d.name}`);}));
    root.querySelectorAll('[data-wallpaper]').forEach(b=>b.onclick=()=>{system.state.settings.wallpaper=b.dataset.wallpaper;system.save();applySettings();});
    root.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{system.state.settings.accent=b.dataset.color;system.state.settings.accentRgb=b.dataset.rgb;system.save();applySettings();});
    root.querySelector('[data-welcome]').onchange=e=>{system.state.settings.showWelcome=e.target.checked;system.save();};root.querySelector('[data-motion]').onchange=e=>{system.state.settings.reduceMotion=e.target.checked;system.save();applySettings();};
    root.querySelector('[data-backup]').onclick=()=>download(`flinux-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(system.state,null,2),'application/json');
    root.querySelector('[data-import]').onclick=()=>root.querySelector('[data-backup-file]').click();
    root.querySelector('[data-backup-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw new Error('Säkerhetskopian är för stor (max 5 MB).');const data=JSON.parse(await file.text());if(!data.filesystem||!data.user||!Array.isArray(data.installed))throw new Error('Det här är ingen flinux-säkerhetskopia.');if(confirm('Ersätta ditt nuvarande virtuella system med säkerhetskopian?')){if(system.importState(data))location.reload();}}catch(error){toast(error.message);}e.target.value='';};
    root.querySelector('[data-reset]').onclick=()=>{if(confirm('Radera alla virtuella flinux-filer, paket och inställningar?'))system.reset();};
    const unsubscribe=system.onChange(draw);draw();return unsubscribe;
  }
  return {renderWelcome,renderFiles,renderKate,renderDiscover,renderSettings};
}
